language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run webpack
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 9a08f13dcc32fb03a8490c2191c533b8915cb824
  local_dir: public
  on:
    branch: master