env:
  global:
    secure: "n+AD7KRcivyNqMRs5icKbVMPJ8jj3ra7bixKiuJvyt5tSNHWpGMu+51jgNcnHxu0wZMpGaEHfJATs6/3++0iO0C0ZiMA/dHUrKY6x2zU8Ac6xmMdPfCnsl/7/XJYV1Peu18Pa5Dtuf5inIum9PV78jTD1veOa5ZUIyOkOBLSJUk945ifY+TyVH45JBGPjsdYrNV91WPFNbLQ4+bocRtxRvRIAs+MDcMnSvQiRx2RHgw84qsZUXI1mMIM4B7YEK6VxTvSvm0a7DQrwdo71YEniZSo9vlj0VUGxEEx2QThoyA7XSjxWuJVliyQmYj40NQoJQnBhWwwiYO88HaDEaACxxaRN+977kisqhbfYzoAl44dt6S2z6XCQt+CiAwwA9rs7K0ZSoA93o+fOz5IhpLKvyJlqZcfBQ1C9Raxr5/9iB1X3Rh/R5orxB4DjAuXqZmaj0Wbv4MbDqxQO7VxzuQKgvKE9E25NvJzKlK1sReQ/Wl7CvMqPKQ8By1e2kovMYmi0eHswxudDGz/N0RqlewjIG8h7W6NPTRqcnwQh+P6kJT3LsaSiGBZ0Zn4F3tenvsdT4XJpMCFz4JIJYMhfhIsgQ9Cxng4tEQkMJwcZ3HVWzUO1GarkcHrOzL0iBVaU2bTAor57yyux9Gz5iAWDVmiYgNxD5Dx51y46zaa9lH8PTY="
language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master